# cmake_minimum_required(VERSION 3.20)

# project(ContainerProject CXX)

# set(CMAKE_CXX_STANDARD 17)
# set(CMAKE_CXX_STANDARD_REQUIRED True)

# add_executable(my_app
#     main.cpp
#     Container.cpp
#     overloads.cpp
#     Point.cpp
#     templates.cpp
# )

program: *.cpp
	g++ *.cpp -o main && ./main